#!/usr/bin/env bun

// Reports which languages the upgrade automation can handle unattended.
//
// Not every language can be bumped by rewriting files. Some base images track
// a version unrelated to the language, some tags are more precise than the
// Dockerfile name, and some templates pin the version in a file nothing knows
// about. This finds all three, so the answer comes from the templates as they
// are today rather than from a list someone has to remember to update.
//
//   bun scripts/language-upgrade/check-language-support.ts --templates-repo ../language-templates
//   bun scripts/language-upgrade/check-language-support.ts --templates-repo ../language-templates --format markdown

import { Command, Option } from "commander";
import ansiColors from "ansi-colors";
import fs from "fs";
import path from "path";
import { glob } from "glob";

import { baseImageTag, currentDockerfile, dockerfileVersion, locateVersionToken } from "./update-language-templates";
import { pinnedFilesForLanguage } from "./version-pins";

type Support = "supported" | "unsupported";

type LanguageReport = {
  language: string;
  version: string;
  baseImage: string;
  // Bumping language-templates has to construct the new Dockerfile, so it can
  // only work when the base image tag carries the language's version.
  templatesBump: Support;
  // Why the base image tag cannot be rewritten, if it cannot.
  templatesBlocker?: string;
  // Files holding the current version that no pin covers. These block nothing,
  // but either operation would leave them stale.
  unpinnedFiles: string[];
  pinnedFiles: string[];
};

// Files that hold a version but are regenerated by their own tooling rather
// than edited, so leaving them to the repair loop is correct.
const LOCKFILES = [
  "uv.lock",
  "Cargo.lock",
  "package-lock.json",
  "bun.lockb",
  "bun.lock",
  "go.sum",
  "manifest.toml",
  "gradle.lockfile",
  "mix.lock",
  // Records the Bundler version, which can coincide with Ruby's: Bundler 4.0.9
  // alongside Ruby 4.0.
  "Gemfile.lock",
  "pubspec.lock",
  "packages.lock.json",
];

// Visual Studio's own version lives here (MinimumVisualStudioVersion =
// 10.0.40219.1), which collides with .NET 10.0 and means nothing for an upgrade.
const IGNORED_EXTENSIONS = [".sln"];

function isNoisyFile(relativePath: string): boolean {
  return LOCKFILES.includes(path.basename(relativePath)) || IGNORED_EXTENSIONS.includes(path.extname(relativePath));
}

// Matches the version, and also any more precise form of it: for a Dockerfile
// named zig-0.16 this finds "0.16" and "0.16.0", but not "0.161" or "10.16".
//
// The more precise form is the point. Zig's build.zig.zon pins
// ".minimum_zig_version = 0.16.0", and an exact-only match missed it, which is
// the same precision trap that makes Docker tags like "elixir:1.19.5" refuse.
function versionMentionPattern(version: string): RegExp {
  return new RegExp(`(?<![\\d.])${version.replace(/\./g, "\\.")}(?:\\.\\d+)*(?![\\d.])`);
}

// Finds files under code/ that mention the current version but that no pin
// covers. An upgrade would leave these stale, which is how a language ends up
// half-upgraded and failing in a way that is hard to attribute.
function findUnpinnedVersionFiles(languageRootDir: string, version: string, pinnedFiles: string[]): string[] {
  const codeDir = path.join(languageRootDir, "code");

  if (!fs.existsSync(codeDir)) {
    return [];
  }

  const candidates = glob.sync(path.join(codeDir, "**/*"), { nodir: true, dot: true });

  return candidates
    .filter((filePath) => {
      const relativePath = path.relative(languageRootDir, filePath);

      if (pinnedFiles.includes(relativePath) || isNoisyFile(relativePath)) {
        return false;
      }

      let contents: string;

      try {
        contents = fs.readFileSync(filePath, "utf8");
      } catch {
        return false;
      }

      return versionMentionPattern(version).test(contents);
    })
    .map((filePath) => path.relative(languageRootDir, filePath));
}

export function checkLanguage(templatesRepoDir: string, languageSlug: string): LanguageReport {
  const languageRootDir = path.join(templatesRepoDir, "languages", languageSlug);
  const dockerfile = currentDockerfile(languageRootDir);
  const version = dockerfileVersion(dockerfile);
  const tag = baseImageTag(dockerfile.contents);
  const pinnedFiles = pinnedFilesForLanguage(languageRootDir, languageSlug);

  const blocker =
    tag === null
      ? "no FROM line with a tagged image"
      : (() => {
          const located = locateVersionToken(tag, version);
          return "error" in located ? located.error : undefined;
        })();

  return {
    language: languageSlug,
    version: version,
    baseImage: tag === null ? "(untagged)" : tag,
    templatesBump: blocker ? "unsupported" : "supported",
    templatesBlocker: blocker,
    unpinnedFiles: findUnpinnedVersionFiles(languageRootDir, version, pinnedFiles),
    pinnedFiles: pinnedFiles,
  };
}

export function checkAllLanguages(templatesRepoDir: string): LanguageReport[] {
  const languagesDir = path.join(templatesRepoDir, "languages");
  const slugs = fs
    .readdirSync(languagesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  return slugs.map((slug) => checkLanguage(templatesRepoDir, slug));
}

// Trims the trailing rationale, which is useful in a failure message but too
// long for a table cell.
function shortBlocker(blocker: string): string {
  return blocker.split(". Refusing")[0].replace(/^tag "[^"]*" /, "");
}

function printText(reports: LanguageReport[]): void {
  const bumpable = reports.filter((report) => report.templatesBump === "supported");
  const blocked = reports.filter((report) => report.templatesBump === "unsupported");
  const stale = reports.filter((report) => report.unpinnedFiles.length > 0);

  // Upgrading a course copies the Dockerfile out of language-templates
  // verbatim, so nothing about the base image constrains it. Only bumping the
  // templates has to build a new Dockerfile, and that is what the base image
  // can block. Reporting one number for both would understate what is
  // automatable, which is what this split is here to avoid.
  console.log("");
  console.log(ansiColors.bold(`Course upgrades: all ${reports.length} languages`));
  console.log(ansiColors.dim("  course-sdk upgrade-language copies the Dockerfile from language-templates,"));
  console.log(ansiColors.dim("  so the base image never has to be rewritten here"));

  console.log("");
  console.log(ansiColors.bold(`language-templates bumps: ${bumpable.length} of ${reports.length}`));
  console.log("");

  for (const report of bumpable) {
    console.log(`  ${ansiColors.green("ok")}  ${report.language.padEnd(12)} ${report.version.padEnd(9)} ${report.baseImage}`);
  }

  console.log("");

  for (const report of blocked) {
    console.log(`  ${ansiColors.red("no")}  ${report.language.padEnd(12)} ${report.version.padEnd(9)} ${report.baseImage}`);
    console.log(`      ${ansiColors.dim(shortBlocker(report.templatesBlocker!))}`);
  }

  console.log("");
  console.log(ansiColors.bold(`Version pins not covered: ${stale.length}`));
  console.log(ansiColors.dim("  these hold the current version but no pin touches them, so either"));
  console.log(ansiColors.dim("  operation would leave them stale"));
  console.log("");

  if (stale.length === 0) {
    console.log(`  ${ansiColors.green("none")}`);
  }

  for (const report of stale) {
    console.log(`  ${ansiColors.yellow("!")}   ${report.language.padEnd(12)} ${report.unpinnedFiles.join(", ")}`);
  }

  console.log("");
}

function printMarkdown(reports: LanguageReport[]): void {
  console.log("| Language | Version | Base image | Templates bump | Why not |");
  console.log("| --- | --- | --- | --- | --- |");

  for (const report of reports) {
    const why = report.templatesBlocker ? shortBlocker(report.templatesBlocker) : "";
    console.log(
      `| ${report.language} | ${report.version} | \`${report.baseImage}\` | ${report.templatesBump === "supported" ? "yes" : "no"} | ${why} |`,
    );
  }
}

if (import.meta.main) {
  const program = new Command();

  program
    .name("check-language-support")
    .description("Report which languages the upgrade automation can handle unattended")
    .requiredOption("--templates-repo <path>", "path to a language-templates checkout")
    .addOption(new Option("--language <slug>", "check a single language instead of all of them"))
    .addOption(new Option("--format <format>", "output format").choices(["text", "markdown", "json"]).default("text"))
    .action((options) => {
      const reports = options.language
        ? [checkLanguage(options.templatesRepo, options.language)]
        : checkAllLanguages(options.templatesRepo);

      if (options.format === "json") {
        console.log(JSON.stringify(reports, null, 2));
      } else if (options.format === "markdown") {
        printMarkdown(reports);
      } else {
        printText(reports);
      }
    });

  program.parse(process.argv);
}
