#!/usr/bin/env bun

// Reports which languages the upgrade automation can handle unattended.
//
// Not every language can be bumped by rewriting files. Some base images track
// a version unrelated to the language, some tags are more precise than the
// Dockerfile name, and some templates pin the version in a file nothing knows
// about. This finds all three, so the answer comes from the templates as they
// are today rather than from a list someone has to remember to update.
//
//   bun scripts/language-upgrade/check-language-support.ts --templates-repo ../language-templates
//   bun scripts/language-upgrade/check-language-support.ts --templates-repo ../language-templates --format markdown

import { Command, Option } from "commander";
import ansiColors from "ansi-colors";
import fs from "fs";
import path from "path";
import { glob } from "glob";

import { baseImageTag, currentDockerfile, dockerfileVersion, locateVersionToken } from "./update-language-templates";
import { pinnedFilesForLanguage } from "./version-pins";

type Support = "supported" | "unsupported";

type LanguageReport = {
  language: string;
  version: string;
  baseImage: string;
  support: Support;
  // Why the base image tag cannot be rewritten, if it cannot.
  blocker?: string;
  // Files holding the current version that no pin covers. These do not block a
  // bump, but they would be left stale by one.
  unpinnedFiles: string[];
  pinnedFiles: string[];
};

// Files that hold a version but are regenerated by their own tooling rather
// than edited, so leaving them to the repair loop is correct.
const LOCKFILES = [
  "uv.lock",
  "Cargo.lock",
  "package-lock.json",
  "bun.lockb",
  "bun.lock",
  "go.sum",
  "manifest.toml",
  "gradle.lockfile",
  "mix.lock",
];

function isLockfile(relativePath: string): boolean {
  return LOCKFILES.includes(path.basename(relativePath));
}

// Finds files under code/ that mention the current version but that no pin
// covers. A bump would leave these stale, which is how a language ends up
// half-upgraded and failing in a way that is hard to attribute.
function findUnpinnedVersionFiles(languageRootDir: string, version: string, pinnedFiles: string[]): string[] {
  const codeDir = path.join(languageRootDir, "code");

  if (!fs.existsSync(codeDir)) {
    return [];
  }

  const candidates = glob.sync(path.join(codeDir, "**/*"), { nodir: true, dot: true });

  return candidates
    .filter((filePath) => {
      const relativePath = path.relative(languageRootDir, filePath);

      if (pinnedFiles.includes(relativePath) || isLockfile(relativePath)) {
        return false;
      }

      let contents: string;

      try {
        contents = fs.readFileSync(filePath, "utf8");
      } catch {
        return false;
      }

      // Bounded so "1.26" does not match inside "1.26.5" or "21.26".
      return new RegExp(`(?<![\\d.])${version.replace(/\./g, "\\.")}(?![\\d.])`).test(contents);
    })
    .map((filePath) => path.relative(languageRootDir, filePath));
}

export function checkLanguage(templatesRepoDir: string, languageSlug: string): LanguageReport {
  const languageRootDir = path.join(templatesRepoDir, "languages", languageSlug);
  const dockerfile = currentDockerfile(languageRootDir);
  const version = dockerfileVersion(dockerfile);
  const tag = baseImageTag(dockerfile.contents);
  const pinnedFiles = pinnedFilesForLanguage(languageRootDir, languageSlug);

  const blocker =
    tag === null
      ? "no FROM line with a tagged image"
      : (() => {
          const located = locateVersionToken(tag, version);
          return "error" in located ? located.error : undefined;
        })();

  return {
    language: languageSlug,
    version: version,
    baseImage: tag === null ? "(untagged)" : tag,
    support: blocker ? "unsupported" : "supported",
    blocker: blocker,
    unpinnedFiles: findUnpinnedVersionFiles(languageRootDir, version, pinnedFiles),
    pinnedFiles: pinnedFiles,
  };
}

export function checkAllLanguages(templatesRepoDir: string): LanguageReport[] {
  const languagesDir = path.join(templatesRepoDir, "languages");
  const slugs = fs
    .readdirSync(languagesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  return slugs.map((slug) => checkLanguage(templatesRepoDir, slug));
}

// Trims the trailing rationale, which is useful in a failure message but too
// long for a table cell.
function shortBlocker(blocker: string): string {
  return blocker.split(". Refusing")[0].replace(/^tag "[^"]*" /, "");
}

function printText(reports: LanguageReport[]): void {
  const supported = reports.filter((report) => report.support === "supported");
  const unsupported = reports.filter((report) => report.support === "unsupported");

  console.log("");
  console.log(ansiColors.bold(`Automatable (${supported.length})`));

  for (const report of supported) {
    const note = report.unpinnedFiles.length > 0 ? ansiColors.yellow(`  unpinned: ${report.unpinnedFiles.join(", ")}`) : "";
    console.log(`  ${ansiColors.green("ok")}  ${report.language.padEnd(12)} ${report.version.padEnd(9)} ${report.baseImage}${note}`);
  }

  console.log("");
  console.log(ansiColors.bold(`Needs a human (${unsupported.length})`));

  for (const report of unsupported) {
    console.log(`  ${ansiColors.red("no")}  ${report.language.padEnd(12)} ${report.version.padEnd(9)} ${report.baseImage}`);
    console.log(`      ${ansiColors.dim(shortBlocker(report.blocker!))}`);

    // For these the unpinned file is often where the version really lives, so
    // it points at what an upgrade would have to touch instead.
    if (report.unpinnedFiles.length > 0) {
      console.log(`      ${ansiColors.dim(`version also appears in: ${report.unpinnedFiles.join(", ")}`)}`);
    }
  }

  console.log("");
}

function printMarkdown(reports: LanguageReport[]): void {
  console.log("| Language | Version | Base image | Automatable | Why not |");
  console.log("| --- | --- | --- | --- | --- |");

  for (const report of reports) {
    const why = report.blocker ? shortBlocker(report.blocker) : "";
    console.log(
      `| ${report.language} | ${report.version} | \`${report.baseImage}\` | ${report.support === "supported" ? "yes" : "no"} | ${why} |`,
    );
  }
}

if (import.meta.main) {
  const program = new Command();

  program
    .name("check-language-support")
    .description("Report which languages the upgrade automation can handle unattended")
    .requiredOption("--templates-repo <path>", "path to a language-templates checkout")
    .addOption(new Option("--language <slug>", "check a single language instead of all of them"))
    .addOption(new Option("--format <format>", "output format").choices(["text", "markdown", "json"]).default("text"))
    .action((options) => {
      const reports = options.language
        ? [checkLanguage(options.templatesRepo, options.language)]
        : checkAllLanguages(options.templatesRepo);

      if (options.format === "json") {
        console.log(JSON.stringify(reports, null, 2));
      } else if (options.format === "markdown") {
        printMarkdown(reports);
      } else {
        printText(reports);
      }
    });

  program.parse(process.argv);
}
