// Bumps the language version wherever it is pinned inside a language's
// templates: config.yml's required_executable, and the dependency manifest.
//
// Both the language-templates layout (languages/<slug>/) and the course layout
// (starter_templates/<slug>/) hold config.yml next to code/, so pin paths are
// relative to that shared root.
//
// Every pin is only rewritten when the version it currently holds matches the
// version we are upgrading from. That guard is what keeps this from mangling
// versions that merely look similar:
//
//   kotlin  config.yml  "gradle (9.4.1)"     Gradle, not Kotlin 2.3
//   haskell config.yml  "stack (24.33)"      Stack, not GHC 9.10
//   kotlin  build.gradle.kts  of(24)         Java toolchain, not Kotlin
//   gleam   config.yml  "gleam (1.14.0)"     already out of sync with 1.16
//
// None of those match the old version, so all of them are left alone.

import fs from "fs";
import path from "path";
import semver from "semver";
import { glob } from "glob";

export type PinOutcome = {
  path: string;
  status: "updated" | "skipped" | "missing";
  before?: string;
  after?: string;
  reason?: string;
};

type Pin = {
  // Glob relative to the language root. A glob because C#'s project file
  // carries a mustache placeholder in its name.
  pathGlob: string;
  // Must have exactly three capture groups: prefix, version, suffix.
  pattern: RegExp;
};

const REQUIRED_EXECUTABLE_PIN: Pin = {
  pathGlob: "config.yml",
  pattern: /^(\s*required_executable:\s*"?[^\s"(]+\s*\()([^)]*)(\))/m,
};

// Lockfiles are deliberately absent. Python's uv.lock also carries
// requires-python, but a lockfile should be regenerated by its tool rather than
// patched by regex; if that leaves the build unhappy, the repair loop runs
// "uv lock".
const MANIFEST_PINS: Record<string, Pin[]> = {
  csharp: [{ pathGlob: "code/*.csproj", pattern: /(<TargetFramework>net)([\d.]+)(<\/TargetFramework>)/ }],
  elixir: [{ pathGlob: "code/mix.exs", pattern: /(elixir:\s*"~>\s*)([\d.]+)(")/ }],
  go: [{ pathGlob: "code/go.mod", pattern: /^(go\s+)(\d[\d.]*)(\s*)$/m }],
  // stack.yaml also has "resolver: lts-24.33", the Stackage snapshot, which
  // moves independently of GHC. Only the compiler line is targeted.
  haskell: [{ pathGlob: "code/stack.yaml", pattern: /^(compiler:\s*ghc-)(\d[\d.]*)(\s*)$/m }],
  java: [
    { pathGlob: "code/pom.xml", pattern: /(<maven\.compiler\.source>)(\d[\d.]*)(<\/maven\.compiler\.source>)/ },
    { pathGlob: "code/pom.xml", pattern: /(<maven\.compiler\.target>)(\d[\d.]*)(<\/maven\.compiler\.target>)/ },
    { pathGlob: "code/pom.xml", pattern: /(<java\.version>)(\d[\d.]*)(<\/java\.version>)/ },
  ],
  python: [{ pathGlob: "code/pyproject.toml", pattern: /^(requires-python\s*=\s*">=\s*)([\d.]+)(")/m }],
  rust: [{ pathGlob: "code/Cargo.toml", pattern: /^(rust-version\s*=\s*")([\d.]+)(")/m }],
};

function coerceOrNull(version: string): semver.SemVer | null {
  return semver.coerce(version);
}

// Rewrite at whatever precision the existing value uses, so "go 1.26.0" stays
// three components while "rust-version = 1.96" stays two.
function renderAtSamePrecision(newVersion: string, existing: string): string {
  const coerced = semver.coerce(newVersion);

  if (coerced === null) {
    throw new Error(`Could not parse "${newVersion}" as a version`);
  }

  const componentCount = Math.min(existing.split(".").length, 3);

  return [coerced.major, coerced.minor, coerced.patch].slice(0, componentCount).join(".");
}

function applyPin(languageRootDir: string, pin: Pin, oldVersion: string, newVersion: string): PinOutcome[] {
  const matchedPaths = glob.sync(path.join(languageRootDir, pin.pathGlob));

  if (matchedPaths.length === 0) {
    return [{ path: pin.pathGlob, status: "missing" }];
  }

  return matchedPaths.map((filePath) => {
    const relativePath = path.relative(languageRootDir, filePath);
    const contents = fs.readFileSync(filePath, "utf8");
    const match = contents.match(pin.pattern);

    if (!match) {
      return { path: relativePath, status: "skipped" as const, reason: "no version pin found" };
    }

    const existingVersion = match[2];
    const existingCoerced = coerceOrNull(existingVersion);
    const oldCoerced = coerceOrNull(oldVersion);

    // The guard: only touch a version that is the one we are upgrading from.
    if (existingCoerced === null || oldCoerced === null || !semver.eq(existingCoerced, oldCoerced)) {
      return {
        path: relativePath,
        status: "skipped" as const,
        before: existingVersion,
        reason: `holds "${existingVersion}", which is not the version being upgraded from ("${oldVersion}")`,
      };
    }

    const replacement = renderAtSamePrecision(newVersion, existingVersion);

    if (replacement === existingVersion) {
      return { path: relativePath, status: "skipped" as const, before: existingVersion, reason: "already at the target version" };
    }

    fs.writeFileSync(filePath, contents.replace(pin.pattern, `$1${replacement}$3`));

    return { path: relativePath, status: "updated" as const, before: existingVersion, after: replacement };
  });
}

// languageRootDir is languages/<slug> in language-templates, or
// starter_templates/<slug> in a course repo.
export function applyVersionPins(languageRootDir: string, languageSlug: string, oldVersion: string, newVersion: string): PinOutcome[] {
  const pins = [REQUIRED_EXECUTABLE_PIN, ...(MANIFEST_PINS[languageSlug] || [])];

  return pins.flatMap((pin) => applyPin(languageRootDir, pin, oldVersion, newVersion));
}
